# -*- coding: utf-8 -*-
"""24-09-04-hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCq-wfLqtIgMLbwpSrZgkWP6Wc0Z8CvH
"""

print("Hello World!!")

print("Hello Python")

import pylab as py

x_deg = py.arange(-180, 180+1)
x_rad = py.deg2rad(x_deg)
y = py.sin(x_rad)

py.plot(x_deg, y)

py.xlabel('x(deg)')
py.ylabel('sin(x)')
py.grid(True)

print("Hello Python")
print("우리 모두 파이썬과 친하게 지내 봅시다")
print("파이썬으로 지루한 작업을 자동화 해 봅시다")